<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import axios from 'axios'
import CodeEditor from '../components/CodeEditor.vue'
import { installAntiCheat } from '../utils/antiCheat'

type Question = { id: string; ordinal: number; title: string; statement: string; max_score?: number; time_limit_ms?: number; memory_limit_kb?: number }
type ExamPayload = { title?: string; status?: string; start_time?: string; end_time?: string; server_time?: string; remaining_seconds?: number; waiting?: boolean; questions?: Question[]; student_id?: string; student_name?: string; client_ip?: string; network_verified?: boolean }
const route = useRoute(); const router = useRouter(); const examId = computed(() => String(route.params.id || '')); const identity = localStorage.getItem('username') || '考生'
const isWaiting = ref(true); const switching = ref(false); const loadingError = ref(''); const exam = ref<ExamPayload>({}); const question = ref<Question>({ id: '', ordinal: 1, title: '', statement: '' }); const code = ref(''); const version = ref(0); const saved = ref('尚未保存'); const output = ref(''); const remaining = ref(0); const candidateId = ref('—'); const candidateName = ref(identity); const clientIp = ref('正在核验…'); const networkVerified = ref(false)
let clockTimer: number | undefined; let pollTimer: number | undefined; let debounce: number | undefined; let stopCheat: (() => void) | undefined; let loadingQuestions = false
const waitingCountdown = computed(() => formatDuration(remaining.value)); const examCountdown = computed(() => formatDuration(remaining.value)); const examTitle = computed(() => exam.value.title || 'LabProctor 计算机程序设计上机考试'); const statusText = computed(() => isWaiting.value ? '● 考场等待中 · 统一机考严禁喧哗' : '● 考试进行中 · 全程监控已激活')
function formatDuration(total: number) { const seconds = Math.max(0, Math.floor(total)); return `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds / 60) % 60).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }
function setClock(payload: ExamPayload) { if (payload.start_time) remaining.value = Math.max(0, Math.ceil((Date.parse(payload.start_time) - Date.parse(payload.server_time || new Date().toISOString())) / 1000)); else if (typeof payload.remaining_seconds === 'number') remaining.value = Math.max(0, payload.remaining_seconds) }
function shouldWait(payload: ExamPayload) { const status = String(payload.status || '').toLowerCase(); const beforeStart = payload.start_time ? Date.parse(payload.start_time) > Date.parse(payload.server_time || new Date().toISOString()) : false; return Boolean(payload.waiting) || status === 'pending' || status === 'draft' || beforeStart }
function applyMeta(payload: ExamPayload) { exam.value = payload; setClock(payload); candidateId.value = payload.student_id || candidateId.value; candidateName.value = payload.student_name || candidateName.value; clientIp.value = payload.client_ip || clientIp.value; networkVerified.value = payload.network_verified !== false }
async function requestStatus() { if (!examId.value) { loadingError.value = '缺少考试编号，无法进入考试。'; return }; try { const { data } = await axios.get<ExamPayload>(`/api/v1/exams/${examId.value}`); applyMeta(data); if (!shouldWait(data) && isWaiting.value) await enterExam(data) } catch (error: any) { loadingError.value = error.response?.data?.error || '考试状态暂时无法获取，请稍候。' } }
async function enterExam(payload: ExamPayload) { if (loadingQuestions) return; loadingQuestions = true; switching.value = true; try { applyMeta(payload); if (!payload.questions?.length) throw new Error('试卷题目尚未发布，请联系监考教师。'); question.value = payload.questions[0]; const draft = await axios.get(`/api/v1/exams/${examId.value}/questions/${question.value.id}/draft`); code.value = draft.data.code || ''; version.value = draft.data.version || 0; isWaiting.value = false; loadingError.value = ''; stopCheat?.(); stopCheat = installAntiCheat(examId.value) } catch (error: any) { loadingError.value = error.message || error.response?.data?.error || '试卷加载失败。' } finally { loadingQuestions = false; window.setTimeout(() => { switching.value = false }, 250) } }
async function save() { if (isWaiting.value || !question.value.id) return; saved.value = '正在自动保存…'; try { const result = await axios.put(`/api/v1/exams/${examId.value}/questions/${question.value.id}/draft`, { code: code.value, version: version.value }); version.value = result.data.version; saved.value = `草稿已同步至云端（版本号：v${version.value}） · ${new Date().toLocaleTimeString()}` } catch { saved.value = '草稿保存失败，将在下次自动保存时重试' } }
watch(code, () => { if (!isWaiting.value) { if (debounce) window.clearTimeout(debounce); debounce = window.setTimeout(save, 2000) } }); async function sample() { if (!isWaiting.value && question.value.id) { const result = await axios.post(`/api/v1/exams/${examId.value}/questions/${question.value.id}/run-sample`, { code: code.value }); output.value = `执行结果：已加入样例调试队列（${result.data.sample_cases} 个样例）` } }; async function submit() { if (!isWaiting.value && window.confirm('确定要提交整套试卷吗？交卷后试卷将立即锁定，不可再修改代码或调试，系统将对全卷进行正式机器判题。')) await axios.post(`/api/v1/exams/${examId.value}/submit`, { confirm: true }) }; function logout() { localStorage.clear(); router.replace('/login') }
onMounted(async () => { await requestStatus(); clockTimer = window.setInterval(() => { if (remaining.value > 0) remaining.value--; if (isWaiting.value && remaining.value === 0) requestStatus() }, 1000); pollTimer = window.setInterval(requestStatus, 5000) }); onBeforeUnmount(() => { stopCheat?.(); if (clockTimer) window.clearInterval(clockTimer); if (pollTimer) window.clearInterval(pollTimer); if (debounce) window.clearTimeout(debounce) })
</script>
<template>
  <main :class="['exam-shell', { 'waiting-shell': isWaiting, 'active-shell': !isWaiting, 'is-switching': switching }]">
    <section v-if="isWaiting" class="waiting-room" aria-live="polite"><div class="waiting-mark">{{ statusText }}</div><h1>{{ examTitle }}</h1><p class="waiting-subtitle">考生候考室</p><div class="candidate-card"><div><span>考生学号</span><strong>{{ candidateId }}</strong></div><div><span>考生姓名</span><strong>{{ candidateName }}</strong></div><div><span>当前机房终端 IP</span><strong>{{ clientIp }}</strong><em :class="{ verified: networkVerified }">{{ networkVerified ? '✓ 机房网络环境验证通过' : '正在进行机房网络环境验证' }}</em></div></div><div class="countdown-label">距离正式开考还剩：</div><div class="countdown">{{ waitingCountdown }}</div><p class="clock-note">时间基准：已与考场服务器权威时钟校准，修改本机时间无效</p><div class="rules"><h2>考场纪律红线</h2><p>1. 考试开始后全屏作弊监控将自动激活，任何失焦、切屏、最小化行为均将毫秒级记入考纪审计；</p><p>2. 本次考试采用整卷快照评测，单题仅提供调试，考试结束前请务必点击整卷交卷；</p><p>3. 模板代码区域受只读保护，请勿尝试篡改框架代码。</p></div><p class="waiting-status"><span class="breathing-dot"></span>系统正在等待统一开考指令，到达开考时间将自动载入试卷，无需手动刷新...</p><p v-if="loadingError" class="error">{{ loadingError }}</p></section>
    <section v-else class="workbench"><header><div><p class="status-line">{{ statusText }}</p><h1>LabProctor OJ - 在线考试系统</h1></div><div>考生：{{ candidateName }} <button @click="logout">退出登录</button><br>考试剩余时间：{{ examCountdown }}<small>（服务端基准时钟同步）</small></div></header><p v-if="loadingError" class="error">{{ loadingError }}</p><section class="workspace-grid"><aside><h2>题目列表</h2><h3>第 {{ question.ordinal }} 题：{{ question.title }}</h3><p>{{ question.statement }}</p><p>满分：{{ question.max_score || 0 }} 分</p><p>时间限制：{{ question.time_limit_ms || 0 }} ms</p><p>内存限制：{{ question.memory_limit_kb || 0 }} KB</p><p class="tip">提示：灰色区域为教师预设模板框架，不可修改；请在指定区域编写您的代码</p><button @click="sample">▶ 运行样例调试（不计入成绩）</button><p>{{ saved }}</p><h3>调试输出面板</h3><pre>{{ output || '执行结果：等待样例调试' }}</pre></aside><article><CodeEditor v-model="code" /></article></section><footer><button @click="save">立即保存草稿</button><button class="submit" @click="submit">整套试卷交卷</button></footer></section>
  </main>
</template>
<style scoped>
:global(*){box-sizing:border-box}.exam-shell{min-height:100vh;transition:opacity .28s ease;font:14px system-ui}.is-switching{opacity:.25}.waiting-shell{background:#030303;color:#fff}.waiting-room{width:min(920px,calc(100% - 36px));margin:auto;padding:clamp(42px,8vh,100px) 0 50px;text-align:center}.waiting-mark{color:#ff3b30;font-weight:800;letter-spacing:.08em;font-size:14px}.waiting-room h1{margin:27px 0 4px;font-size:clamp(28px,5vw,50px);letter-spacing:.04em}.waiting-subtitle{margin:0;color:#a7a7a7;letter-spacing:.3em}.candidate-card{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin:45px 0 42px;background:#555;border:1px solid #555}.candidate-card>div{display:flex;min-height:98px;padding:18px;flex-direction:column;justify-content:center;background:#0d0d0d}.candidate-card span{color:#aaa;font-size:12px}.candidate-card strong{margin:7px 0;font-size:19px}.candidate-card em{color:#777;font-size:12px;font-style:normal}.candidate-card em.verified{color:#5ee38c}.countdown-label{color:#aaa;font-size:16px}.countdown{margin:5px 0 7px;color:#fff;font:700 clamp(52px,10vw,94px)/1 ui-monospace,monospace;letter-spacing:.07em}.clock-note{color:#777;font-size:12px}.rules{margin:40px auto;text-align:left;border-top:1px solid #383838;border-bottom:1px solid #383838;padding:21px 8px;color:#d0d0d0;line-height:1.8}.rules h2{margin:0 0 10px;color:#ff5b52;font-size:15px}.rules p{margin:5px 0}.waiting-status{margin:33px 0 0;color:#aaa;font-size:13px}.breathing-dot{display:inline-block;width:8px;height:8px;margin-right:9px;border-radius:50%;background:#fff;animation:breathe 1.5s ease-in-out infinite}@keyframes breathe{50%{opacity:.2;box-shadow:0 0 15px #fff}}.error{padding:10px;color:#ffb4b0;background:#4a1717;border-radius:5px}.active-shell{background:#f5f7fb;color:#172b4d}.workbench{min-height:100vh;padding:20px}.workbench header,.workbench footer{display:flex;justify-content:space-between;align-items:center;background:#fff;padding:12px 20px;border-radius:8px}.workbench h1{margin:0}.status-line{margin:0 0 4px;color:#067647;font-weight:700}.workbench small{display:block;color:#667085;font-weight:normal}.workspace-grid{display:grid;grid-template-columns:30% 70%;gap:12px;margin:12px 0}.workspace-grid aside{padding:16px;border-radius:8px;background:#fff}.tip{padding:10px;color:#475467;background:#f0f0f0}.workbench button{padding:8px 14px;border:0;border-radius:5px;cursor:pointer}.submit{background:#b42318;color:#fff}.workbench pre{padding:10px;color:#9fe870;background:#111;white-space:pre-wrap}.workbench footer{gap:12px;justify-content:flex-end}@media(max-width:720px){.candidate-card{grid-template-columns:1fr}.workbench{padding:10px}.workbench header{align-items:flex-start;gap:12px;flex-direction:column}.workspace-grid{grid-template-columns:1fr}.countdown{font-size:48px}}
</style>
