<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'
const router=useRouter();const account=ref('');const password=ref('');const showPassword=ref(false);const remember=ref(true);const error=ref('');const loading=ref(false)
async function login(){error.value='';if(!account.value||!password.value){error.value='请输入学号/工号和密码';return}loading.value=true;try{const r=await axios.post('/api/v1/auth/login',{student_id:account.value,password:password.value});const d=r.data;localStorage.setItem('token',d.token);localStorage.setItem('role',d.role);localStorage.setItem('username',d.username||d.student_id||account.value);if(!remember.value)localStorage.setItem('session_only','true');await router.replace(d.role==='student'?'/exam/1':'/teacher/dashboard')}catch(e){error.value='学号或密码错误，请核对后重试'}finally{loading.value=false}}
function github(){window.location.href='/api/v1/auth/github'}
</script>
<template><main><section class="card"><h1>LabProctor OJ</h1><h2>机房专属在线编程考试系统</h2><p class="sub">统一身份认证 · 安全机考 · 全程留痕</p><form @submit.prevent="login"><label>👤 学号 / 工号<input v-model="account" placeholder="请输入您的校内学号或教工号" autocomplete="username"></label><label>🔒 登录密码<div class="password"><input v-model="password" :type="showPassword?'text':'password'" placeholder="请输入登录密码" autocomplete="current-password"><button type="button" @click="showPassword=!showPassword">{{showPassword?'隐藏':'显示'}}</button></div></label><label class="remember"><input v-model="remember" type="checkbox"> 记住本次登录</label><p v-if="error" class="error">{{error}}</p><button class="login" :disabled="loading">{{loading?'正在验证身份…':'立即进入考场 / 监考系统'}}</button></form><div class="divider">或使用第三方账号</div><button class="github" @click="github">使用 GitHub 账号授权登录/绑定</button><aside><b>测试环境账号</b><br>学生测试账号：20240001 / Student@123<br>教师测试账号：teacher_01 / Teacher@123<br>管理员测试账号：admin / Admin@123</aside></section></main></template>
<style scoped>main{min-height:100vh;display:grid;place-items:center;background:linear-gradient(135deg,#102a43,#1f4b99);font:15px system-ui}.card{width:390px;padding:36px;background:#fff;border-radius:14px;box-shadow:0 20px 60px #071b33aa}h1{text-align:center;color:#163b70;margin:0;font-size:30px}h2{text-align:center;font-size:18px;margin:8px 0}.sub{text-align:center;color:#667085}form{display:grid;gap:14px;margin-top:24px}label{display:grid;gap:6px;font-weight:600}input{padding:11px;border:1px solid #d0d5dd;border-radius:6px;font:inherit}.password{display:flex}.password input{flex:1}.password button{border:1px solid #d0d5dd;background:#f8f9fa}.remember{display:block;font-weight:normal}.remember input{vertical-align:middle}.login,.github{padding:12px;border:0;border-radius:6px;color:#fff;cursor:pointer}.login{background:#1f4b99}.github{width:100%;background:#24292f}.divider{text-align:center;color:#667085;margin:18px 0}.error{color:#b42318;background:#fef3f2;padding:8px;margin:0}.card aside{margin-top:22px;padding:12px;background:#fff8e6;color:#7a4b00;line-height:1.8;font-size:12px}</style>
