FROM docker.m.daocloud.io/library/golang:1.22-bookworm AS build
WORKDIR /src
ENV GOPROXY=https://goproxy.cn,direct
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o /out/worker ./cmd/worker
FROM docker.m.daocloud.io/library/gcc:12-bookworm
COPY --from=build /out/worker /worker
RUN id -u judge >/dev/null 2>&1 || useradd -m -u 1000 judge
USER judge
CMD ["/worker"]
