FROM docker.m.daocloud.io/library/golang:1.22-bookworm AS build
WORKDIR /src
ENV GOPROXY=https://goproxy.cn,direct
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o /out/server ./cmd/server
FROM gcr.m.daocloud.io/distroless/static-debian12:latest
COPY --from=build /out/server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
