package router

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/sunjingru123/LabProctor-OJ/internal/handler"
	"github.com/sunjingru123/LabProctor-OJ/internal/middleware"
)

type Deps struct { Auth middleware.Auth; Login *handler.AuthHandler; Guard *middleware.ExamGuard; Student *handler.StudentExam; Teacher *handler.TeacherExam; Review *handler.TeacherReview }
func cors() gin.HandlerFunc { return func(c *gin.Context) { origin:=c.GetHeader("Origin");if origin=="http://localhost:5173" { c.Header("Access-Control-Allow-Origin",origin);c.Header("Vary","Origin") } else if origin=="" { } else { c.Header("Access-Control-Allow-Origin","*") };c.Header("Access-Control-Allow-Methods","GET, POST, PUT, DELETE, OPTIONS");c.Header("Access-Control-Allow-Headers","Authorization, Content-Type, X-Requested-With");if c.Request.Method==http.MethodOptions { c.AbortWithStatus(http.StatusNoContent);return };c.Next() } }
func New(d Deps)*gin.Engine { r:=gin.New();r.Use(gin.Recovery(),cors());public:=r.Group("/api/v1/auth");public.POST("/login",d.Login.Login);api:=r.Group("/api/v1",d.Auth.Require());api.GET("/student/my-exams",middleware.RequireRole("student"),d.Student.MyExams);student:=api.Group("/exams/:id",middleware.RequireRole("student"),d.Guard.Student());student.GET("",d.Student.Detail);student.GET("/questions/:qid/draft",d.Student.Draft);student.PUT("/questions/:qid/draft",d.Student.SaveDraft);student.POST("/questions/:qid/run-sample",d.Student.RunSample);student.POST("/submit",d.Student.Submit);student.POST("/anti-cheat/event",d.Student.AntiCheat);teacher:=api.Group("/teacher/exams",middleware.RequireRole("teacher","admin"));teacher.GET("",d.Teacher.List);teacher.POST("",d.Teacher.Create);teacher.PUT("/:id",d.Teacher.Update);teacher.POST("/:id/publish",d.Teacher.Publish);teacher.POST("/:id/start",d.Teacher.Start);teacher.GET("/:id/dashboard",d.Teacher.Dashboard);teacher.POST("/:id/force-end",d.Teacher.ForceEnd);teacher.GET("/:id/questions",d.Teacher.Questions);teacher.POST("/:id/questions",d.Teacher.CreateQuestion);teacher.PUT("/:id/questions/:qid",d.Teacher.UpdateQuestion);teacher.DELETE("/:id/questions/:qid",d.Teacher.DeleteQuestion);teacher.GET("/:id/participants",d.Teacher.Participants);teacher.POST("/:id/participants/import",d.Teacher.ImportParticipants);teacher.PUT("/:id/participants/:student_id",d.Teacher.UpdateParticipant);teacher.PUT("/:id/reviews/:student_id",d.Review.Update);teacher.GET("/:id/exports/sources.zip",d.Review.SourceZip);teacher.GET("/:id/exports/grades.xlsx",d.Review.Grades);teacher.GET("/:id/exports/screen-logs.xlsx",d.Review.ScreenLogs);return r }
